# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Infopedia
email: djurdjevicboris@hotmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
minimal_mistakes_skin: default
search: true
baseurl: "/"
excerpt_separator: "<!-- end excerpt -->"
url: "https://borisdj.net"
logo: "/assets/images/icon.jpg"
author:
  name     : "Boris Djurdjevic"
  avatar   : "/assets/images/avatar.jpg"
  bio      : "Code Designer, Passionate Programmer, Software Architect, Problem Solver (OpenSource, .Net, EF-Core, Blazor)"
  email: djurdjevicboris@hotmail.com
  links:
  - label: "* About"
    icon: "about"
    url: "https://borisdj.net/about"
  - label: "Twitter"
    icon: "fab fa-fw fa-twitter-square"
    url: "https://twitter.com/boris.dj"
  - label: "GitHub"
    icon: "fab fa-fw fa-github"
    url: "https://github.com/borisdj"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/boris.dj"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/borisdj"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      read_time: true
      share: true
      sidebar:
        nav: "docs"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      sidebar:
        nav: "docs"
category_archive:
  type: money
  path: /categories/
tag_archive:
  type: money
  path: /tags/
